name = "priyanka-portfolio"
type = "javascript"
main = "build/index.js"  # or correct server entry from your Remix build

compatibility_date = "2024-01-01"

kv_namespaces = [
  { id = "MY_KV", binding = "MY_KV" }
]

[build]
command = "npm run build"
cwd = "."

[site]
bucket = "./build/client"

[build.upload]
format = "service-worker"
